openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
  description: Specification for OPENAPI course
  termsOfService: http://example.com/terms
  contact:
    name: Antony George
    url: https://antonyjoy.george.com
    email: antonyjoy.george@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://dev.example.com
    description: Development
  - url: https://qa.example.com
    description: QA
  - url: https://prod.example.com
    description: Production

paths:
  /v1/customers:
    get:
      responses:
        "200":
          description: List of Customers
          content:
            application/json:
              schema:
                type: array
                minItems: 2
                maxItems: 100
                items:
                  type: string
                  description: Customer Name
                  minLength: 2
                  maxLength: 100
  /v1/beers:
    get:
      responses:
        "200":
          description: List of Beers
        "404":
          description: (Not Fount) response
