openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
  description: Specification for OPENAPI course
  termsOfService: http://example.com/terms
  contact:
    name: Antony George
    url: https://antonyjoy.george.com
    email: antonyjoy.george@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://dev.example.com
    description: Development
  - url: https://qa.example.com
    description: QA
  - url: https://prod.example.com
    description: Production

paths:
  /v1/customers:
    get:
      responses:
        "200":
          description: List of Customers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                items:
                  type: object
                  description: Customer Object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: Antony
                    lastName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: George
                    address:
                      type: object
                      properties:
                        line1:
                          type: string
                          example: 123 street
                        city:
                          type: string
                          example: Trivandrum
                        zipcode:
                          type: string
                          example: 44556
  /v1/beers:
    get:
      responses:
        "200":
          description: List of Beers
        "404":
          description: (Not Fount) response
